import { ArtifactStore, type ArtifactRecord } from "../artifacts/store.js";
import { AuditLog } from "../audit/log.js";
import { workspacePaths } from "../paths.js";
import { ClientRegistry, type ClientRecord } from "../registries/client.js";
import { ProjectRegistry, type ProjectRecord } from "../registries/project.js";

export interface GitHubIssueDraft {
  title: string;
  body: string;
  labels: string[];
  source_artifacts: string[];
}

export interface GitHubIssueDraftResult {
  project: ProjectRecord;
  client?: ClientRecord;
  drafts: GitHubIssueDraft[];
  artifacts: ArtifactRecord[];
}

export interface GitHubIssueDraftDeps {
  projects?: ProjectRegistry;
  clients?: ClientRegistry;
  artifacts?: ArtifactStore;
  audit?: AuditLog;
}

function sourceSection(artifacts: readonly ArtifactRecord[]): string {
  if (artifacts.length === 0) return "- No source artifacts found.";
  return artifacts.map((artifact) => `- ${artifact.type}: ${artifact.id}`).join("\n");
}

function draftBody(args: {
  title: string;
  project: ProjectRecord;
  client?: ClientRecord;
  sourceArtifacts: ArtifactRecord[];
  objective: string;
  acceptance: string[];
}): string {
  const { title, project, client, sourceArtifacts, objective, acceptance } = args;
  return `# ${title}

<!-- bureauos:github-issue-draft project="${project.id}" -->

## Objective

${objective}

## Context

- Client: ${client?.name ?? project.client_id}
- Project: ${project.name}
- Project status: ${project.status}
- Stack: ${project.stack || "tbd"}

## Source Artifacts

${sourceSection(sourceArtifacts)}

## Acceptance Criteria

${acceptance.map((line) => `- ${line}`).join("\n")}

## Policy Notes

This issue was generated by BureauOS. External commitments, pricing, publishing, deployment, and paid spend remain approval-gated.
`;
}

function buildDrafts(args: {
  project: ProjectRecord;
  client?: ClientRecord;
  artifacts: ArtifactRecord[];
}): GitHubIssueDraft[] {
  const { project, client, artifacts } = args;
  const byType = (type: string): ArtifactRecord[] =>
    artifacts.filter((artifact) => artifact.type === type);

  const projectBrief = byType("project-brief");
  const proposal = byType("proposal-brief");
  const pricing = byType("pricing-brief");
  const repository = byType("repository-provisioning-plan");
  const compliance = byType("compliance-review");
  const social = byType("social-post-brief");
  const ads = byType("ad-campaign-brief");

  return [
    {
      title: `Product: finalize scope for ${project.name}`,
      labels: ["type:feature", "stage:product-ready", "agent:product", "needs:decision"],
      source_artifacts: projectBrief.map((artifact) => artifact.id),
      body: draftBody({
        title: `Product: finalize scope for ${project.name}`,
        project,
        client,
        sourceArtifacts: projectBrief,
        objective:
          "Turn the intake into product-ready scope, user stories, and acceptance criteria.",
        acceptance: [
          "Given the owner intake, when Product reviews it, then the issue has user stories and non-goals.",
          "Given open questions remain, when the issue is updated, then each question has an owner-facing decision path.",
          "Given the scope affects pricing, when scope is finalized, then pricing remains approval-gated.",
        ],
      }),
    },
    {
      title: `Delivery: provision repository for ${project.name}`,
      labels: ["type:chore", "stage:intake", "agent:pm"],
      source_artifacts: repository.map((artifact) => artifact.id),
      body: draftBody({
        title: `Delivery: provision repository for ${project.name}`,
        project,
        client,
        sourceArtifacts: repository,
        objective: "Prepare the GitHub repository, labels, and first delivery structure.",
        acceptance: [
          "Given owner approval or project policy, when repository provisioning runs, then the repo exists and is linked in project memory.",
          "Given labels are missing, when setup runs, then BureauOS labels are applied.",
          "Given the repo exists, when setup completes, then project memory references the repository URL.",
        ],
      }),
    },
    {
      title: `Sales: prepare proposal for ${client?.name ?? project.name}`,
      labels: ["type:feature", "stage:intake", "agent:sales", "needs:human"],
      source_artifacts: [...proposal, ...pricing].map((artifact) => artifact.id),
      body: draftBody({
        title: `Sales: prepare proposal for ${client?.name ?? project.name}`,
        project,
        client,
        sourceArtifacts: [...proposal, ...pricing],
        objective: "Draft the client proposal and pricing options without sending them externally.",
        acceptance: [
          "Given proposal and pricing drafts, when Sales prepares the proposal, then final price is not committed.",
          "Given the proposal is ready, when it is marked final, then owner approval is required before sending.",
          "Given the client asks for scope changes, when the proposal changes, then margin risk is recalculated.",
        ],
      }),
    },
    {
      title: `Compliance: review external commitments for ${project.name}`,
      labels: ["type:chore", "stage:intake", "agent:compliance", "risk:medium", "needs:decision"],
      source_artifacts: compliance.map((artifact) => artifact.id),
      body: draftBody({
        title: `Compliance: review external commitments for ${project.name}`,
        project,
        client,
        sourceArtifacts: compliance,
        objective:
          "Verify approval gates before proposal send, public content, ads, or client commitments.",
        acceptance: [
          "Given public content is drafted, when it references the client, then client permission is required.",
          "Given final scope or price is proposed, when it leaves BureauOS, then owner approval exists.",
          "Given ads are requested, when a campaign is launched, then budget and claims are approved.",
        ],
      }),
    },
    {
      title: `Growth: draft proof-safe content for ${project.name}`,
      labels: ["type:feature", "stage:intake", "agent:content", "risk:low"],
      source_artifacts: [...social, ...ads].map((artifact) => artifact.id),
      body: draftBody({
        title: `Growth: draft proof-safe content for ${project.name}`,
        project,
        client,
        sourceArtifacts: [...social, ...ads],
        objective: "Prepare growth assets without publishing or exposing client-private details.",
        acceptance: [
          "Given content is drafted, when no client permission exists, then the draft avoids client name, logo, screenshots, and result claims.",
          "Given ads are drafted, when budget is absent, then campaign launch remains blocked.",
          "Given owner approves publishing, when content is published, then the approval record is linked.",
        ],
      }),
    },
  ];
}

export class GitHubIssueDraftService {
  private readonly projects: ProjectRegistry;
  private readonly clients: ClientRegistry;
  private readonly artifacts: ArtifactStore;
  private readonly audit: AuditLog;

  constructor(
    private readonly workspaceRoot: string,
    deps: GitHubIssueDraftDeps = {},
  ) {
    this.projects = deps.projects ?? new ProjectRegistry(workspaceRoot);
    this.clients = deps.clients ?? new ClientRegistry(workspaceRoot);
    this.artifacts = deps.artifacts ?? new ArtifactStore(workspaceRoot);
    this.audit = deps.audit ?? new AuditLog(workspacePaths(workspaceRoot).auditLog);
  }

  async draftForProject(projectSlug: string): Promise<GitHubIssueDraftResult> {
    const project = await this.projects.get(projectSlug);
    if (!project) throw new Error(`project not found: ${projectSlug}`);

    const allClients = await this.clients.list();
    const client = allClients.find((item) => item.id === project.client_id);
    const sourceArtifacts = await this.artifacts.list({ project_id: project.id });
    const drafts = buildDrafts({ project, client, artifacts: sourceArtifacts });
    const artifacts: ArtifactRecord[] = [];

    for (const draft of drafts) {
      artifacts.push(
        await this.artifacts.write({
          type: "github-issue-draft",
          createdBy: "supreme_coordinator",
          projectId: project.id,
          ...(client ? { clientId: client.id } : {}),
          metadata: {
            title: draft.title,
            labels: draft.labels,
            source_artifacts: draft.source_artifacts,
          },
          body: `${draft.body}\n\n## Labels\n\n${draft.labels.map((label) => `- ${label}`).join("\n")}\n`,
        }),
      );
    }

    await this.audit.append({
      actor: "supreme_coordinator",
      action: "github.issue_drafts.generated",
      target: project.id,
      result: "ok",
    });

    return { project, client, drafts, artifacts };
  }
}
